.TH "car" 3 "Вт 29 Окт 2019" "lab_02_doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
car \- Структура, предназначенная для обработки данных об автомобилях  

.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "char \fBmodel\fP [\fBCHAR_LEN\fP]"
.br
.RI "Модель машины "
.ti -1c
.RI "char \fBcountry\fP [\fBCHAR_LEN\fP]"
.br
.RI "Страна-производитель "
.ti -1c
.RI "char \fBcolor\fP [\fBCHAR_LEN\fP]"
.br
.RI "Цвет "
.ti -1c
.RI "int \fBcost\fP"
.br
.RI "Цена "
.ti -1c
.RI "int \fBstate\fP"
.br
.RI "Состояние 1 - б/у, 0 - нет "
.ti -1c
.RI "int \fBflag_del\fP"
.br
.RI "Флаг на удаление "
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      int \fBguar\fP"
.br
.RI "Гарантия "
.ti -1c
.RI "   } \fBcar_new\fP"
.br
.RI "Структура, для новых автомобилей "
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      int \fByear\fP"
.br
.RI "Год выпуска "
.ti -1c
.RI "      int \fBmileage\fP"
.br
.RI "Пробег "
.ti -1c
.RI "      int \fBrepairs\fP"
.br
.RI "Кол-во ремонтов "
.ti -1c
.RI "      int \fBowner\fP"
.br
.RI "Кол-во владельцев "
.ti -1c
.RI "   } \fBcar_used\fP"
.br
.RI "Структура, для б\&.у\&. автомобилей "
.ti -1c
.RI "} \fBcondition\fP"
.br
.RI "Union, включающий в себя дополнительный сведения об автомобилях "
.in -1c
.SH "Подробное описание"
.PP 
Структура, предназначенная для обработки данных об автомобилях 
.SH "Данные класса"
.PP 
.SS "struct { \&.\&.\&. } 
         car::car_new"

.PP
Структура, для новых автомобилей 
.SS "struct { \&.\&.\&. } 
         car::car_used"

.PP
Структура, для б\&.у\&. автомобилей 
.SS "char car::color[\fBCHAR_LEN\fP]"

.PP
Цвет 
.SS "union { \&.\&.\&. } 
     car::condition"

.PP
Union, включающий в себя дополнительный сведения об автомобилях 
.SS "int car::cost"

.PP
Цена 
.SS "char car::country[\fBCHAR_LEN\fP]"

.PP
Страна-производитель 
.SS "int car::flag_del"

.PP
Флаг на удаление 
.SS "int car::guar"

.PP
Гарантия 
.SS "int car::mileage"

.PP
Пробег 
.SS "char car::model[\fBCHAR_LEN\fP]"

.PP
Модель машины 
.SS "int car::owner"

.PP
Кол-во владельцев 
.SS "int car::repairs"

.PP
Кол-во ремонтов 
.SS "int car::state"

.PP
Состояние 1 - б/у, 0 - нет 
.SS "int car::year"

.PP
Год выпуска 

.SH "Автор"
.PP 
Автоматически создано Doxygen для lab_02_doxygen из исходного текста\&.
