.TH "car_sort" 3 "Вт 29 Окт 2019" "lab_02_doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
car_sort \- Структура ключей  

.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "int \fBname\fP"
.br
.RI "Name\&. "
.ti -1c
.RI "int \fBid\fP"
.br
.RI "id "
.ti -1c
.RI "int \fBflag_del_sort\fP"
.br
.RI "Флаг удаления "
.in -1c
.SH "Подробное описание"
.PP 
Структура ключей 
.SH "Данные класса"
.PP 
.SS "int car_sort::flag_del_sort"

.PP
Флаг удаления 
.SS "int car_sort::id"

.PP
id 
.SS "int car_sort::name"

.PP
Name\&. 

.SH "Автор"
.PP 
Автоматически создано Doxygen для lab_02_doxygen из исходного текста\&.
